//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPH
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChitietHoadon
    {
        public int ID { get; set; }
        public Nullable<int> HoadonID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Soluong { get; set; }
    
        public virtual Hoadon Hoadon { get; set; }
        public virtual Product Product { get; set; }
    }
}
