//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoadon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hoadon()
        {
            this.ChitietHoadons = new HashSet<ChitietHoadon>();
        }
    
        public int ID { get; set; }
        public int NhanvienID { get; set; }
        public int KhachhangID { get; set; }
        public int PhonghatID { get; set; }
        public Nullable<bool> LoaiPhong { get; set; }
        public Nullable<int> Thanhtien { get; set; }
        public Nullable<System.DateTime> ThoigianBatdau { get; set; }
        public Nullable<int> Tienphong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChitietHoadon> ChitietHoadons { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual Phonghat Phonghat { get; set; }
    }
}
