//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phonghat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phonghat()
        {
            this.Hoadons = new HashSet<Hoadon>();
        }
    
        public int ID { get; set; }
        public string TenPhong { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<bool> Trangthai { get; set; }
        public Nullable<bool> IsReserved { get; set; }
        public Nullable<int> IsReserverdBy { get; set; }
        public Nullable<int> Dongia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoadon> Hoadons { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
