//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPH
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeLogin
    {
        public int ID { get; set; }
        public Nullable<int> NhanvienID { get; set; }
        public Nullable<System.DateTime> LoginAt { get; set; }
        public Nullable<System.DateTime> LogoutAt { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
